spring:
  docker:
    compose:
      lifecycle-management: start-and-stop

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:3003

logging:
  level:
    com.example.attendance: DEBUG
    org.springframework.security: DEBUG
