services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: attendance
      POSTGRES_USER: attendance
      POSTGRES_PASSWORD: attendance
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
